### ISSUE TITLE
Localized Enum type field

### ISSUE THREAD

**Issue by draza67** [mcintyre321/mvc.jquery.datatables#116]
I have a column of enum type, and each enum value is localized so I added display attributes with reference to appropriate resource library. It troubles me that I did not find enough effective way to both a column and text in the checkbox column filter displayed correctly.
On the one hand, it is not possible to apply custom instance method that converts the value of the enum field to the corresponding string from resources directly into a LINQ to Entities, but the request must be done as LINQ to objects(insert .ToList() method before "userView" object creation). Thus the datatable performance are unacceptably disrupted.
On the other hand, it seems to me that it is impossible to be the enum field content  different from checkbox Column filter (vm.FilterOn(string columnName).CheckBoxes(params string[] options)).
What is the best way to get localized Enum field with correctly localized checkbox filter?

**Comment by mcintyre321** [comment]
You can use a (transform function)[https://github.com/mcintyre321/mvc.jquery.datatables/blob/master/Mvc.JQuery.Datatables.Example/Controllers/HomeController.cs#L40] to localize the enum after the query has taken place.

For localised filter options, I think it might be necessary to for you to extend the library or maybe columnfilters.js in order to separate display text from value.

**Comment by draza67** [comment]
Thank You for Your fast answer.
Yes, I made it by transform function, but checkbox column filter values must be same as value before transform function. It's clear now, that there is need to extend code.
