### ISSUE TITLE
TableTools are not working both on the Demo site and both in my project

### ISSUE THREAD

**Issue by MrCsabaToth** [mcintyre321/mvc.jquery.datatables#142]
Does it supposed to work?
The code still seems to rely on the copy_csv_xls_pdf.swf. Whereas newer DataTables use JSZip and pdfmake pdfmake/vfs_fonts. Flash export is no longer required. Please point me out the current state so I can fix this.

**Comment by mcintyre321** [comment]
The table tools work in my browser (chrome), but it's likely that the new versions work better across browsers. 

I don't update the project to be compatible with the latest datatables unless I have a need, or someone sends me a pull request, so that's the reason. If you send a PR with an update, and the tests and demo site execute correctly I will be happy to accept it.
