### ISSUE TITLE
Render partial sample link is broken

### ISSUE THREAD

**Issue by papyr** [mcintyre321/mvc.jquery.datatables#154]
Hi, just wanted to let you know the link is broken for render sample

**Comment by mcintyre321** [comment]
Cheers, I'll fix it when I get a chance. The examples are in the repo if
you are looking for them

On 6 Aug 2016 16:00, "papyr" <notifications@github.com> wrote:

Hi, just wanted to let you know the link is broken for render sample

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mcintyre321/mvc.jquery.datatables/issues/154>, or mute
the thread

**Comment by papyr** [comment]
ok thanks and great repo BTW! :+1:
