### ISSUE TITLE
Cannot find mvc.jquery.datatables.core Nuget package 

### ISSUE THREAD

**Issue by pratikvasani** [mcintyre321/mvc.jquery.datatables#162]
Hi ,

I am not able to find mvc.jquery.datatables.core  in the Nuget repo.
has this been removed ? 
https://www.nuget.org/packages?q=mvc.jquery.datatables.core

Because of this i am not able to refer DataTablesParam class in my project

**Comment by mcintyre321** [comment]
It's been renamed .Common, sorry!

**Comment by pratikvasani** [comment]
@mcintyre321  so the core package is not needed any more right ?

What version has this been changed in . As i was also getting errors like DataTablesParam class found in 2 location  when i tried to add the  main nuget package .

**Comment by mcintyre321** [comment]
Yup, no longer needed. I think it was a major version number I increased,
when I added dot net core support.





On 16 May 2017 11:55, "Pratik" <notifications@github.com> wrote:

@mcintyre321 <https://github.com/mcintyre321> so the core package is not
needed any more right ?

What version has this been changed in . As i was also getting errors like
DataTablesParam class found in 2 location when i tried to add the main
nuget package .

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mcintyre321/mvc.jquery.datatables/issues/162#issuecomment-301746986>,
or mute the thread

**Comment by mcshaz** [comment]
Can this issue be closed?

**Comment by pratikvasani** [comment]
Yes , I have resolved my issue by removing the old mvc.jquery.datatables.core library and adding the new Common library. 

For anyone who runs into this issue , this will create confusion & throw errors if projects in your solution have different version of the package which was the case with me.
